import React, { useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useAuth } from '../context/AuthContext';
import { Palette } from '../theme';
import { Card, PrimaryButton } from '../components/UI';

export function AccountScreen({ c, onClose }: { c: Palette; onClose(): void }) {
  const auth = useAuth(); const [mode, setMode] = useState<'signin'|'signup'>('signin'); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [newPassword, setNewPassword] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const execute = async () => { setBusy(true); setMessage(''); try { if (mode === 'signin') await auth.signIn(email.trim(), password); else setMessage(await auth.signUp(email.trim(), password)); } catch (e) { setMessage(e instanceof Error ? e.message : 'Something went wrong.'); } finally { setBusy(false); } };
  if (auth.session) return <View style={[s.root, { backgroundColor: c.bg }]}><Header c={c} onClose={onClose}/><View style={s.signed}><View style={[s.avatar, { backgroundColor: c.surface2 }]}><Ionicons name="person" size={34} color={c.primary}/></View><Text style={[s.title, { color: c.text }]}>Cloud backup is on</Text><Text style={[s.body, { color: c.muted }]}>{auth.session.user.email}{'\n'}Completed walks, summaries, goals and preferences sync when online.</Text><Card c={c} style={s.card}><TextInput autoCapitalize="none" secureTextEntry placeholder="New password (optional)" placeholderTextColor={c.muted} value={newPassword} onChangeText={setNewPassword} style={[s.input, { backgroundColor: c.surface2, borderColor: c.line, color: c.text }]}/>{newPassword.length >= 6 ? <PrimaryButton c={c} title="Update Password" icon="key" onPress={() => auth.updatePassword(newPassword).then(() => { setNewPassword(''); Alert.alert('Password updated'); }).catch(e => Alert.alert('Could not update password', e.message))}/> : null}<Pressable onPress={() => auth.signOut().catch(e => Alert.alert('Could not sign out', e.message))}><Text style={[s.link, { color: c.text }]}>Sign out</Text></Pressable><Pressable onPress={() => Alert.alert('Delete account and cloud data?', 'This permanently deletes your Supabase account and all synced data. Local activity stays on this device.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: () => auth.deleteAccount().catch(e => Alert.alert('Could not delete account', e.message)) }])}><Text style={[s.link, { color: c.danger }]}>Delete account & cloud data</Text></Pressable></Card></View></View>;
  return <KeyboardAvoidingView style={[s.root, { backgroundColor: c.bg }]} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><Header c={c} onClose={onClose}/><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.form}><Text style={[s.title, { color: c.text }]}>{mode === 'signin' ? 'Welcome back.' : 'Back up your strides.'}</Text><Text style={[s.body, { color: c.muted }]}>{auth.configured ? 'Your app remains fully usable offline. Sign in only if you want encrypted transport and cross-device cloud restoration.' : 'Cloud sync is optional and is not configured in this build. Add the public Supabase environment values to enable accounts.'}</Text><TextInput autoCapitalize="none" autoComplete="email" keyboardType="email-address" placeholder="Email" placeholderTextColor={c.muted} value={email} onChangeText={setEmail} style={[s.input, { backgroundColor: c.surface, borderColor: c.line, color: c.text }]}/><TextInput autoCapitalize="none" autoComplete={mode === 'signup' ? 'new-password' : 'current-password'} secureTextEntry placeholder="Password" placeholderTextColor={c.muted} value={password} onChangeText={setPassword} style={[s.input, { backgroundColor: c.surface, borderColor: c.line, color: c.text }]}/>{message ? <Text style={[s.message, { color: message.includes('wrong') || message.includes('Invalid') ? c.danger : c.primary }]}>{message}</Text> : null}<PrimaryButton c={c} disabled={busy || !auth.configured || !email || password.length < 6} title={busy ? 'Please wait…' : mode === 'signin' ? 'Sign In' : 'Create Account'} icon={mode === 'signin' ? 'log-in' : 'person-add'} onPress={execute}/><Pressable onPress={() => { setMode(mode === 'signin' ? 'signup' : 'signin'); setMessage(''); }}><Text style={[s.link, { color: c.primary }]}>{mode === 'signin' ? 'New to Stride? Create an account' : 'Already have an account? Sign in'}</Text></Pressable>{mode === 'signin' ? <Pressable onPress={async () => { if (!email) return setMessage('Enter your email first.'); try { await auth.resetPassword(email.trim()); setMessage('Password reset email sent.'); } catch (e) { setMessage(e instanceof Error ? e.message : 'Could not send reset email.'); } }}><Text style={[s.link, { color: c.muted }]}>Forgot password?</Text></Pressable> : null}</ScrollView></KeyboardAvoidingView>;
}
function Header({ c, onClose }: { c: Palette; onClose(): void }) { return <View style={s.header}><Pressable accessibilityLabel="Close account" onPress={onClose}><Ionicons name="close" size={27} color={c.text}/></Pressable><Text style={[s.headerTitle, { color: c.text }]}>Account</Text><View style={{ width: 27 }}/></View>; }
const s = StyleSheet.create({ root: { flex: 1 }, header: { paddingTop: 58, paddingHorizontal: 22, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, headerTitle: { fontWeight: '800', fontSize: 17 }, form: { padding: 24, paddingTop: 70, gap: 16 }, title: { fontSize: 31, fontWeight: '900', letterSpacing: -1 }, body: { fontSize: 14, lineHeight: 22, marginBottom: 12, textAlign: 'center' }, input: { height: 56, borderWidth: 1, borderRadius: 17, paddingHorizontal: 17, fontSize: 16 }, link: { textAlign: 'center', fontWeight: '700', paddingVertical: 8 }, message: { fontSize: 13, textAlign: 'center' }, signed: { flex: 1, alignItems: 'center', padding: 24, paddingTop: 80 }, avatar: { width: 80, height: 80, borderRadius: 30, alignItems: 'center', justifyContent: 'center' }, card: { alignSelf: 'stretch', marginTop: 28, gap: 8 } });
