<<<<<<< ours
import React,{useEffect,useRef}from'react';
import{ActivityIndicator,Animated,Pressable,StyleSheet,Text,View}from'react-native';
import Svg,{Circle}from'react-native-svg';
import{Ionicons}from'@expo/vector-icons';
import{Palette}from'../theme';
export function Card({children,c,style}:{children:React.ReactNode;c:Palette;style?:object}){return <View style={[styles.card,{backgroundColor:c.surface,borderColor:c.line},style]}>{children}</View>}
export function ProgressRing({value,size=210,c,children}:{value:number;size?:number;c:Palette;children:React.ReactNode}){const animated=useRef(new Animated.Value(0)).current;useEffect(()=>{Animated.spring(animated,{toValue:Math.min(value,1),useNativeDriver:true,friction:8}).start()},[value,animated]);const stroke=15,r=(size-stroke)/2,circ=2*Math.PI*r;return <View style={{width:size,height:size,alignItems:'center',justifyContent:'center'}}><Svg width={size} height={size} style={StyleSheet.absoluteFill}><Circle cx={size/2} cy={size/2} r={r} stroke={c.surface2} strokeWidth={stroke} fill="none"/><Circle cx={size/2} cy={size/2} r={r} stroke={c.primary} strokeWidth={stroke} fill="none" strokeDasharray={`${circ} ${circ}`} strokeDashoffset={circ*(1-Math.min(value,1))} strokeLinecap="round" rotation="-90" origin={`${size/2},${size/2}`}/></Svg>{children}</View>}
export function Metric({icon,value,label,c}:{icon:keyof typeof Ionicons.glyphMap;value:string;label:string;c:Palette}){return <View style={styles.metric}><View style={[styles.metricIcon,{backgroundColor:c.surface2}]}><Ionicons name={icon} size={18} color={c.primary}/></View><Text style={[styles.metricValue,{color:c.text}]}>{value}</Text><Text style={[styles.label,{color:c.muted}]}>{label}</Text></View>}
export function PrimaryButton({title,icon='arrow-forward',onPress,c,disabled=false,danger=false}:{title:string;icon?:keyof typeof Ionicons.glyphMap;onPress():void;c:Palette;disabled?:boolean;danger?:boolean}){return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={({pressed})=>[styles.button,{backgroundColor:danger?c.danger:c.primary,opacity:disabled ? .45 : pressed ? .82 : 1}]}><Text style={[styles.buttonText,{color:c.primaryText}]}>{title}</Text><Ionicons name={icon} size={19} color={c.primaryText}/></Pressable>}
export function EmptyState({icon,title,body,c}:{icon:keyof typeof Ionicons.glyphMap;title:string;body:string;c:Palette}){return <View style={styles.empty}><View style={[styles.emptyIcon,{backgroundColor:c.surface2}]}><Ionicons name={icon} size={30} color={c.primary}/></View><Text style={[styles.emptyTitle,{color:c.text}]}>{title}</Text><Text style={[styles.emptyBody,{color:c.muted}]}>{body}</Text></View>}
export function Loading({c}:{c:Palette}){return <View style={[styles.loading,{backgroundColor:c.bg}]}><ActivityIndicator color={c.primary} size="large"/><Text style={{color:c.muted,marginTop:14}}>Preparing your day…</Text></View>}
const styles=StyleSheet.create({card:{borderRadius:24,borderWidth:1,padding:20},metric:{flex:1,alignItems:'center',gap:5},metricIcon:{height:38,width:38,borderRadius:19,alignItems:'center',justifyContent:'center',marginBottom:2},metricValue:{fontSize:16,fontWeight:'700'},label:{fontSize:11,fontWeight:'600'},button:{height:58,borderRadius:20,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:10},buttonText:{fontSize:17,fontWeight:'800'},empty:{alignItems:'center',paddingVertical:44,paddingHorizontal:28},emptyIcon:{height:64,width:64,borderRadius:24,alignItems:'center',justifyContent:'center',marginBottom:18},emptyTitle:{fontSize:20,fontWeight:'800',marginBottom:8},emptyBody:{fontSize:14,lineHeight:21,textAlign:'center'},loading:{flex:1,alignItems:'center',justifyContent:'center'}});
=======
import React, { useEffect, useRef } from '\''react'\'';
import { ActivityIndicator, Animated, Pressable, StyleSheet, Text, View, ViewStyle } from '\''react-native'\'';
import Svg, { Circle, Defs, LinearGradient as SvgGradient, Stop } from '\''react-native-svg'\'';
import { LinearGradient } from '\''expo-linear-gradient'\'';
import { Ionicons } from '\''@expo/vector-icons'\'';
import { Palette, tokens } from '\''../theme'\'';

export function Card({ children, c, style }: { children: React.ReactNode; c: Palette; style?: ViewStyle | ViewStyle[] }) { return <View style={[styles.card, { backgroundColor: c.surface, borderColor: c.line, shadowColor: c.shadow }, style]}>{children}</View>; }
export function ProgressRing({ value, size = 210, c, children }: { value: number; size?: number; c: Palette; children: React.ReactNode }) {
  const scale = useRef(new Animated.Value(.96)).current; useEffect(() => { Animated.spring(scale, { toValue: 1, useNativeDriver: true, friction: 7 }).start(); }, [value, scale]);
  const stroke = 15, r = (size - stroke) / 2, circ = 2 * Math.PI * r;
  return <Animated.View style={{ width: size, height: size, alignItems: '\''center'\'', justifyContent: '\''center'\'', transform: [{ scale }] }}><Svg width={size} height={size} style={StyleSheet.absoluteFill}><Defs><SvgGradient id="ring" x1="0" y1="0" x2="1" y2="1"><Stop offset="0" stopColor={c.primary}/><Stop offset="1" stopColor={c.primary2}/></SvgGradient></Defs><Circle cx={size / 2} cy={size / 2} r={r} stroke={c.surface2} strokeWidth={stroke} fill="none"/><Circle cx={size / 2} cy={size / 2} r={r} stroke="url(#ring)" strokeWidth={stroke} fill="none" strokeDasharray={`${circ} ${circ}`} strokeDashoffset={circ * (1 - Math.min(value, 1))} strokeLinecap="round" rotation="-90" origin={`${size / 2},${size / 2}`}/></Svg>{children}</Animated.View>;
}
export function Metric({ icon, value, label, c, selected = false }: { icon: keyof typeof Ionicons.glyphMap; value: string; label: string; c: Palette; selected?: boolean }) { return <View style={[styles.metric, selected && { backgroundColor: c.surface2 }]}><View style={[styles.metricIcon, { backgroundColor: selected ? c.primary : c.surface2 }]}><Ionicons name={icon} size={18} color={selected ? c.primaryText : c.primary}/></View><Text style={[styles.metricValue, { color: c.text }]}>{value}</Text><Text style={[styles.label, { color: c.muted }]}>{label}</Text></View>; }
export function PrimaryButton({ title, icon = '\''arrow-forward'\'', onPress, c, disabled = false, danger = false }: { title: string; icon?: keyof typeof Ionicons.glyphMap; onPress(): void; c: Palette; disabled?: boolean; danger?: boolean }) { return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={({ pressed }) => [{ opacity: disabled ? .45 : pressed ? .82 : 1, transform: [{ scale: pressed ? .985 : 1 }] }]}><LinearGradient colors={danger ? [c.danger, '\''#C94058'\''] : [c.primary, c.primary2]} start={{ x: 0, y: 0 }} end={{ x: 1, y: 1 }} style={styles.button}><Text style={[styles.buttonText, { color: c.primaryText }]}>{title}</Text><Ionicons name={icon} size={19} color={c.primaryText}/></LinearGradient></Pressable>; }
export function EmptyState({ icon, title, body, c }: { icon: keyof typeof Ionicons.glyphMap; title: string; body: string; c: Palette }) { return <View style={styles.empty}><LinearGradient colors={[c.surface2, c.surface]} style={styles.emptyIcon}><Ionicons name={icon} size={30} color={c.primary}/></LinearGradient><Text style={[styles.emptyTitle, { color: c.text }]}>{title}</Text><Text style={[styles.emptyBody, { color: c.muted }]}>{body}</Text></View>; }
export function Loading({ c, label = '\''Preparing your day…'\'' }: { c: Palette; label?: string }) { return <View style={[styles.loading, { backgroundColor: c.bg }]}><ActivityIndicator color={c.primary} size="large"/><Text style={{ color: c.muted, marginTop: 14 }}>{label}</Text></View>; }
const styles = StyleSheet.create({ card: { borderRadius: tokens.radius.lg, borderWidth: 1, padding: tokens.spacing.lg, shadowOpacity: .12, shadowRadius: 18, shadowOffset: { width: 0, height: 8 }, elevation: 3 }, metric: { flex: 1, alignItems: '\''center'\'', gap: 5, borderRadius: 18, paddingVertical: 6 }, metricIcon: { height: 38, width: 38, borderRadius: 19, alignItems: '\''center'\'', justifyContent: '\''center'\'', marginBottom: 2 }, metricValue: { fontSize: 16, fontWeight: '\''700'\'' }, label: { fontSize: 11, fontWeight: '\''600'\'' }, button: { height: 58, borderRadius: tokens.radius.md, flexDirection: '\''row'\'', alignItems: '\''center'\'', justifyContent: '\''center'\'', gap: 10 }, buttonText: { fontSize: 17, fontWeight: '\''800'\'' }, empty: { alignItems: '\''center'\'', paddingVertical: 44, paddingHorizontal: 28 }, emptyIcon: { height: 64, width: 64, borderRadius: 24, alignItems: '\''center'\'', justifyContent: '\''center'\'', marginBottom: 18 }, emptyTitle: { fontSize: 20, fontWeight: '\''800'\'', marginBottom: 8 }, emptyBody: { fontSize: 14, lineHeight: 21, textAlign: '\''center'\'' }, loading: { flex: 1, alignItems: '\''center'\'', justifyContent: '\''center'\'' } });
>>>>>>> theirs
