<<<<<<< ours
import React from'react';import{StyleSheet,Text,View}from'react-native';import{Palette}from'../theme';
export function WeeklyChart({data,goal,c}:{data:{date:string;label:string;steps:number}[];goal:number;c:Palette}){const max=Math.max(goal,...data.map(d=>d.steps));return <View><View style={s.head}><Text style={[s.title,{color:c.text}]}>This week</Text><Text style={[s.goal,{color:c.muted}]}>Goal {goal.toLocaleString()}</Text></View><View style={s.chart}>{data.map((d,i)=><View key={d.date} style={s.col}><Text style={[s.number,{color:c.muted}]}>{d.steps>0?`${Math.round(d.steps/100)/10}k`:''}</Text><View style={[s.track,{backgroundColor:c.surface2}]}><View style={[s.bar,{height:`${Math.max(5,d.steps/max*100)}%`,backgroundColor:d.steps>=goal?c.primary:i===6?c.primary:c.muted}]}/></View><Text style={[s.day,{color:i===6?c.text:c.muted}]}>{d.label}</Text></View>)}</View></View>}
const s=StyleSheet.create({head:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:22},title:{fontSize:19,fontWeight:'800'},goal:{fontSize:12},chart:{height:148,flexDirection:'row',alignItems:'flex-end',gap:10},col:{flex:1,height:'100%',alignItems:'center'},number:{fontSize:9,height:16},track:{flex:1,width:12,borderRadius:8,justifyContent:'flex-end',overflow:'hidden'},bar:{width:'100%',borderRadius:8},day:{fontSize:11,fontWeight:'700',marginTop:8}});
=======
import React from'\''react'\'';import{StyleSheet,Text,View}from'\''react-native'\'';import{Palette}from'\''../theme'\'';
export function WeeklyChart({data,goal,c}:{data:{date:string;label:string;steps:number}[];goal:number;c:Palette}){const max=Math.max(goal,...data.map(d=>d.steps));return <View><View style={s.head}><Text style={[s.title,{color:c.text}]}>This week</Text><Text style={[s.goal,{color:c.muted}]}>Goal {goal.toLocaleString()}</Text></View><View style={s.chart}>{data.map((d,i)=><View key={d.date} style={s.col}><Text style={[s.number,{color:c.muted}]}>{d.steps>0?`${Math.round(d.steps/100)/10}k`:'\'''\''}</Text><View style={[s.track,{backgroundColor:c.surface2}]}><View style={[s.bar,{height:`${Math.max(5,d.steps/max*100)}%`,backgroundColor:d.steps>=goal?c.primary:i===6?c.primary:c.muted}]}/></View><Text style={[s.day,{color:i===6?c.text:c.muted}]}>{d.label}</Text></View>)}</View></View>}
const s=StyleSheet.create({head:{flexDirection:'\''row'\'',justifyContent:'\''space-between'\'',alignItems:'\''center'\'',marginBottom:22},title:{fontSize:19,fontWeight:'\''800'\''},goal:{fontSize:12},chart:{height:148,flexDirection:'\''row'\'',alignItems:'\''flex-end'\'',gap:10},col:{flex:1,height:'\''100%'\'',alignItems:'\''center'\''},number:{fontSize:9,height:16},track:{flex:1,width:12,borderRadius:8,justifyContent:'\''flex-end'\'',overflow:'\''hidden'\''},bar:{width:'\''100%'\'',borderRadius:8},day:{fontSize:11,fontWeight:'\''700'\'',marginTop:8}});
>>>>>>> theirs
